export const AJOUTER_DOSSIER = "AJOUTER_DOSSIER"
export const AJOUTER_PRESTATION = "AJOUTER_PRESTATION"
export const AJOUTER_ASSURES = "AJOUTER_ASSURES"
export const AJOUTER_AYANTSDROIT = "AJOUTER_AYANTSDROIT"